### ISSUE TITLE
ActiveRecord::RecordNotUnique in registrations#create

### ISSUE THREAD

**Issue by Sartori-RIA** [Sartori-RIA/restaurant_manager_api#3]
## Error in ibuteco-api

**ActiveRecord::RecordNotUnique** in **registrations#create**
PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_organizations_on_phone"
DETAIL:  Key (phone)=(42991613052) already exists.

[View on Bugsnag](https://app.bugsnag.com/cookiecode/ibuteco-api/errors/602e4493dcb8440018fcd225?event_id=602e4493006af2e6e2aa0000&i=gh&m=ci)

## Stacktrace

    app/controllers/registrations_controller.rb:46 - build_organization
    app/controllers/registrations_controller.rb:56 - create_with_organization
    app/controllers/registrations_controller.rb:16 - create

[View full stacktrace](https://app.bugsnag.com/cookiecode/ibuteco-api/errors/602e4493dcb8440018fcd225?event_id=602e4493006af2e6e2aa0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by Leandro-Custodio** [comment]
gostei

**Comment by Sartori-RIA** [comment]
+1
